### PR TITLE
Added an image usage report

### PR DESCRIPTION
**Pull request by cnk**
This is a report for identifying images that are not currently in use. Right now it is very basic - a list of all images on the site and a count of how often they are used. There are links to the image usage page and to the image edit where one can delete the image. It is usuable in its current condition but if anyone wants to extend this report, it might be useful to add a FilterSet that allows filtering by collection and/or by used / not used.

### CODE REVIEW

**Comment by cnk** [comment]
I fixed the sorting issue but am still having trouble changing the query to count how many things reference an image rather than the total number of references. A page using an image as its SEO media image and in the body of the page is counted as 2 references in this query while the number displayed on the image edit page would only count that as 1 use.

**Comment by cnk** [comment]
More info for the "help wanted". The query I am using for this report counts all the lines in the Reference Index that reference a given image. But the usage display on the image edit page shows the count of items referencing the image. These two counts differ when a page uses an image multiple times - for example in the text and as the social media image. This is essential a Django/Wagtail puzzle. You don't need to have the data from wagtail.org to be able to contribute to this issue because you can copy the report into any Wagtail project you have set up and figure out the query there.

**Comment by cnk** [comment]
Discussion for moving the information in this report into the image listing views: https://github.com/wagtail/wagtail/issues/12550

File: wagtailio/images/views.py [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+    ]
+
+    def get_base_queryset(self):
+        # Create the subquery to count matching ReferenceIndex rows
+        reference_index_subquery = (
+            ReferenceIndex.objects.filter(
+                to_content_type=ContentType.objects.get_for_model(WagtailIOImage),
+                # to_object_id is a varchar so we need to cast the image PK to a varchar for comparison
+                to_object_id=Cast(OuterRef("pk"), output_field=CharField()),
+            )
```
Comment (joelwilliam2005) [inline wagtailio/images/views.py:41]: You can add:
```
.values('content_type_id', 'object_id')
.distinct()
```

This approach will create a pair of images and where the image is used. 
And even if an image is used two times in a page, you will have one referencing item as using distinct() will ensure each item is counted only once.

Comment (cnk) [reply wagtailio/images/views.py:41]: @joelwilliam2005 thanks for the attempt. I am not 100% sure where you want me to add those lines, but every place I tried, I get `ProgrammingError at /admin/reports/image_usage_report/
more than one row returned by a subquery used as an expression`

The version that doesn't error (below) this gives the exact same counts as the version in the current PR. 

```reference_index_subquery = (
            ReferenceIndex.objects.filter(
                to_content_type=ContentType.objects.get_for_model(WagtailIOImage),
                # to_object_id is a varchar so we need to cast the image PK to a varchar for comparison
                to_object_id=Cast(OuterRef("pk"), output_field=CharField()),
            )
            .values('to_content_type_id',  cast_to_object_id=Cast("to_object_id", output_field=IntegerField()))
            .distinct()
            .values(count=Count("id"))
        )
```

Comment (cnk) [reply wagtailio/images/views.py:41]: Thanks. That doesn't error - and doesn't change the query results. It is still counting all the lines in the ReferenceIndex table.

Comment (joelwilliam2005) [reply wagtailio/images/views.py:41]: I'll look into it.

Comment (joelwilliam2005) [reply wagtailio/images/views.py:41]: Can you try this approach and see if it works?
```
def get_base_queryset(self):
        # Create the subquery to count distinct items referencing each image
        reference_index_subquery = (
            ReferenceIndex.objects.filter(
                to_content_type=ContentType.objects.get_for_model(Image),
                to_object_id=Cast(OuterRef("pk"), output_field=CharField()),
            )
            .values("object_id", "to_object_id")  
            .distinct()  
            .values('to_object_id')  
            .annotate(count=Count('object_id', distinct=True))  
            .values('count') 
        )
```

Comment (joelwilliam2005) [reply wagtailio/images/views.py:41]: You'll have to import this as well:
`from wagtail.images.models import Image`

Comment (cnk) [reply wagtailio/images/views.py:41]: YES!!!!!!! @joelwilliam2005 can you please push a second commit to this PR branch - but keep WagtailIOImage rather than Image in the to_content_type line? I want you to add this as a commit so it's in your GH history rather than mine.

Comment (joelwilliam2005) [reply wagtailio/images/views.py:41]: Awesome!! Glad to hear that it works.
I've created a PR #509 for it.

**Comment by cnk** [comment]
@vossisboss I think this report is ready to go to production. The counts now match the usage data you get for an individual image and I have added a filter so you can find images used, 0, 1, or multiple times. You can then export them. The export includes the title and description in case you want to use it to prioritize better alt text for images in use.

Screenshot 2025-05-21 at 4 48 34 PM

**Comment by vossisboss** [comment]
This looks good! Thank you so much for contributing this report @cnk! I think this one would be a great one to include in our standard reports too if you want to propose adding it to Wagtail core as well.

**Review by laymonage — COMMENTED** [review]
I tried this at https://wagtail.org/admin/reports/image_usage_report/ but it throws a 500 error

```
ModelChoiceField.__init__() missing 1 required positional argument: 'queryset'
```

Sentry issue (if you have access):
https://torchbox.sentry.io/issues/6640591798/?environment=production&project=1220804&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0

I wonder if this broke after #521 or not. I'll try to look into it when I have time.
